apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xextrapolicyattachments.sixt.com
spec:
  claimNames:
    kind: ExtraPolicyAttachment
    plural: extrapolicyattachments
  group: sixt.com
  names:
    kind: XExtraPolicyAttachment
    plural: xextrapolicyattachments
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: Attaching policy to an already existing role
          properties:
            spec:
              description: Attaching policy to an already existing role
              properties:
                resourceConfig:
                  type: object
                  description: ResourceConfig defines general properties of this AWS resource.
                  properties:
                    environment:
                      type: string
                      default: "Dev"
                    managedBy:
                      type: string
                      default: "Crossplane"
                    serviceName:
                      type: string
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                      - Delete
                      - Orphan
                      type: string
                    providerConfigName:
                      type: string
                      default: "aws-provider-config"
                    bucketName:
                      type: string
                    clusterName:
                      type: string
                      default: "go-main-dev"
                  required:
                  - serviceName
                  - bucketName
              required:
              - resourceConfig
            status:
              description: Define the observed state of the Policy
              properties:
                policyArn:
                  type: string
              type: object
          type: object
