apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xirsas.sixt.com
spec:
  claimNames:
    kind: IRSA
    plural: irsas
  group: sixt.com
  names:
    kind: XIRSA
    plural: xirsas
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: IRSA is the Schema for the irsas API
          properties:
            spec:
              description: IRSASpec defines the desired state of IRSA
              properties:
                k8sProviderConfigRef:
                  description: K8s Provider Config
                  type: string
                awsAccountID:
                  type: string
                eksOIDC:
                  type: string
                permissionsBoundaryArn:
                  type: string
                policyArns:
                  items:
                    type: string
                  type: array
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS
                    resource.
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                      - Delete
                      - Orphan
                      type: string
                    name:
                      description: Set the name of this resource in AWS to the value
                        provided by this field.
                      type: string
                    providerConfigName:
                      type: string
                    region:
                      type: string
                    tags:
                      items:
                        properties:
                          key:
                            type: string
                          value:
                            type: string
                        required:
                        - key
                        - value
                        type: object
                      type: array
                  required:
                  - providerConfigName
                  - region
                  - tags
                  type: object
                serviceAccountName:
                  type: string
              required:
              - awsAccountID
              - eksOIDC
              - serviceAccountName
              - resourceConfig
              - k8sProviderConfigRef
              type: object
            status:
              description: IRSAStatus defines the observed state of IRSA
              properties:
                roleArn:
                  type: string
                roleName:
                  type: string
              type: object
          type: object
