apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xirsas.sixt.com
spec:
  claimNames:
    kind: IRSA
    plural: irsas
  group: sixt.com
  names:
    kind: XIRSA
    plural: xirsas
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: IRSA is the Schema for the irsas API
          properties:
            spec:
              description: IRSASpec defines the desired state of IRSA
              properties:
                k8sProviderConfigRef:
                  description: K8s Provider Config
                  type: string
                  default: "kubernetes-provider-config"
                awsAccountID:
                  type: string
                  default: "227837763243"
                eksOIDC:
                  type: string
                  default: "oidc.eks.eu-central-1.amazonaws.com/id/4A85FB28B0938A6568CAB365A330333B"
                environment:
                  type: string
                  default: "Dev"
                managedBy:
                  type: string
                  default: "Crossplane"
                serviceName:
                  type: string
                  default: "Goorange"
                permissionsBoundaryArn:
                  type: string
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS
                    resource.
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                      - Delete
                      - Orphan
                      type: string
                    name:
                      description: Set the name of this resource in AWS to the value
                        provided by this field.
                      type: string
                    providerConfigName:
                      type: string
                      default: "aws-provider-config"
                    tags:
                      items:
                        properties:
                          key:
                            type: string
                          value:
                            type: string
                        required:
                        - key
                        - value
                        type: object
                      type: array
                  required:
                  - providerConfigName
                  type: object
                serviceAccountName:
                  type: string
                bucketName:
                  type: string
              required:
              - serviceAccountName
              - bucketName
              type: object
            status:
              description: IRSAStatus defines the observed state of IRSA
              properties:
                roleArn:
                  type: string
                roleName:
                  type: string
                policyArn:
                  type: string
              type: object
          type: object
