apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NamespaceBasedResourceName
metadata:
  name: namespace-based-resource-name
spec:
  match:
    # scope: "Cluster"
    kinds:
      - apiGroups: ["sixt.com"]
        kinds: ["ObjectStorage"]
      - apiGroups: ["sixt.com"]
        kinds: ["ExtraPolicyAttachment"]
      - apiGroups: ["sixt.com"]
        kinds: ["IRSA"]
      - apiGroups: ["sixt.com"]
        kinds: ["S3WithIRSA"]
