---
# Creating a config for gatekeeper to collect all the existing namespace on the cluster
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  sync:
    syncOnly:
      - group: ""
        version: "v1"
        kind: "Namespace"
      - group: "sixt.com"
        version: "v1alpha1"
        kind: "S3WithIRSA"
      - group: "sixt.com"
        version: "v1alpha1"
        kind: "ObjectStorage"