---
apiVersion: sixt.com/v1alpha1
kind: IRSA
metadata:
  name: goorange-crossplane-example-bucket-16-irsa
  namespace: crossplane-test-namespace
spec:
  serviceAccountName: goorange-crossplane-example-bucket-16-irsa
  bucketName: goorange-crossplane-example-bucket-16