---
apiVersion: sixt.com/v1alpha1
kind: ObjectStorage
metadata:
  name: goorange-crossplane-example-bucket-6
  namespace: crossplane-test-namespace
spec:
  compositionSelector:
    matchLabels:
      sixt.com/provider: aws
      sixt.com/environment: dev
      s3.sixt.com/configuration: standard
      crossplace.io/xrd: xobjectstorages.sixt.com
  writeConnectionSecretToRef:
    name: bucket-info
  resourceConfig:
    tags:
    - key: Environment
      value: dev
    - key: ServiceName
      value: goorange
    - key: Name
      value: goorange-crossplane-example-bucket-6
    name: goorange-crossplane-example-bucket-6
    providerConfigName: aws-provider-config