---
apiVersion: sixt.com/v1alpha1
kind: S3WithPolicyAttachment
metadata:
  name: goorange-s3-with-policy-attachment-example
  namespace: testing
spec:
  resourceConfig:
    bucketName: goorange-s3-with-policy-attachment-example-bucket-20
    serviceName: com.sixt.service.test