apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ResourceAlreadyManagedByCrossplane
metadata:
  name: resource-already-managed-by-crossplane
spec:
  match:
    kinds:
      - apiGroups: ["sixt.com"]
        kinds: ["S3WithIRSA"]
      - apiGroups: ["sixt.com"]
        kinds: ["S3WithPolicyAttachment"]
