apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3bucket.sixt.com
  labels:
    sixt.com/provider: aws
    sixt.com/environment: dev
    s3.sixt.com/configuration: standard
    crossplace.io/xrd: xobjectstorages.sixt.com
spec:
  compositeTypeRef:
    apiVersion: sixt.com/v1alpha1
    kind: XObjectStorage
  resources:
    - name: s3-bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete
      patches:
        - fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
        - fromFieldPath: spec.resourceConfig.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - fromFieldPath: spec.resourceConfig.environment
          toFieldPath: spec.forProvider.tags.Environment
        - fromFieldPath: spec.resourceConfig.name
          toFieldPath: spec.forProvider.tags.Name
        - fromFieldPath: spec.resourceConfig.managedBy
          toFieldPath: spec.forProvider.tags.ManagedBy
        - fromFieldPath: spec.resourceConfig.serviceName
          toFieldPath: spec.forProvider.tags.ServiceName
        - fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.bucketName
        - fromFieldPath: status.atProvider.arn
          toFieldPath: status.bucketArn
    - name: s3-bucketpublicaccessblock
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketPublicAccessBlock
        spec:
          deletionPolicy: Delete
          blockPublicAcls: true
          blockPublicPolicy: true
          ignorePublicAcls: true
          restrictPublicBuckets: true
          forProvider:
            bucketSelector:
              matchControllerRef: true
      patches:
        - fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
        - fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
    - name: s3-bucketserversideencryptionconfiguration
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketServerSideEncryptionConfiguration
        spec:
          deletionPolicy: Delete
          forProvider:
            bucketSelector:
              matchControllerRef: true
            rule:
              - applyServerSideEncryptionByDefault:
                  - sseAlgorithm: AES256
      patches:
        - fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region